# Site settings
title: 张朝威的博客
email: feelkill2009@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  张朝威的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://feelkill.github.io  # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Zhang Chaowei

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter: 
weibo: 
github: feelkill
instagram: 
linkedin: 

# avatar and Favicon
avatar: /assets/img/monkey_head.jpg # http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# disqus config
disqus:
  shortname: feelkill

# google analytics config
ga:
  id: 
  url: feelkill.github.io

# Build settings
permalink: /:year/:month/:day/:title.html
highlighter: rouge
# highlighter: pygments
markdown: redcarpet # kramdown 
kramdown:
  input:         GFM
  auto_ids:      true
  auto_id_prefix: 'id-'
  # footnote_nr:   1
  # entity_output: as_char
  # toc_levels:    1..6
  # smart_quotes:  lsquo,rsquo,ldquo,rdquo
  # use_coderay:   true

  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         2
  #   coderay_bold_every:        10
  #   coderay_css:               style
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

